import React, { createContext, useState } from 'react';

export const DataContext = createContext();

export const DataProvider = ({ children }) => {
    const [details] = useState([
        {id: 1, name: "hella-magic", projectName: "hella magic store", projectDescription: "From spellbinding crystals to bewitching potions, our curated collection is handpicked to inspire and ignite your imagination. Browse through our shelves and uncover artifacts with ancient wisdom.", clientName: "David piagure", year: 2024, category: "business", liveProjects: "https://www.google.com/", image1: "https://framerusercontent.com/images/qBAjeNJY3IsvVWSmaixag3ucDo.jpeg?scale-down-to=2048", researchDescription: "Informing decision-making: Research provides data and evidence to support design decisions. It helps designers make informed choices about layout, color schemes, typography, and other design elements, leading to more effective and user-friendly websites", designDescription: "Usability and Accessibility: Good design considers the needs and preferences of users, ensuring that the website is easy to navigate and understand. Intuitive navigation, clear hierarchy, and logical organization of content enhance usability and accessibility, allowing users to find what they are looking for quickly and easily", developmentDescription: "Development optimizes the website's performance by optimizing code, reducing file sizes, and improving loading times. A fast-loading website enhances user experience, reduces bounce rates, and improves search engine rankings", image2: "https://framerusercontent.com/images/q5h5RWImSNjBi7JmesOfZtaNOY.jpeg?scale-down-to=2048", conceptDescription: "Informing decision-making: Research provides data and evidence to support design decisions. It helps designers make informed choices about layout, color schemes, typography, and other design elements, leading to more effective and user-friendly websites", image3: "https://framerusercontent.com/images/szdQiOWLK1UFrKRNzNforAVR2vk.jpeg?scale-down-to=2048", image4: "https://framerusercontent.com/images/ss9xXtLYQbblZoYno4pKgCES8U.jpeg?scale-down-to=2048"},
        {id: 2, name: "bci-trading-company", projectName: "BCI stores", projectDescription: "From spellbinding crystals to bewitching potions, our curated collection is handpicked to inspire and ignite your imagination. Browse through our shelves and uncover artifacts with ancient wisdom.", clientName: "David piagure", year: 2024, category: "business", liveProjects: "https://www.google.com/", image1: "https://framerusercontent.com/images/qBAjeNJY3IsvVWSmaixag3ucDo.jpeg?scale-down-to=2048", researchDescription: "Informing decision-making: Research provides data and evidence to support design decisions. It helps designers make informed choices about layout, color schemes, typography, and other design elements, leading to more effective and user-friendly websites", designDescription: "Usability and Accessibility: Good design considers the needs and preferences of users, ensuring that the website is easy to navigate and understand. Intuitive navigation, clear hierarchy, and logical organization of content enhance usability and accessibility, allowing users to find what they are looking for quickly and easily", developmentDescription: "Development optimizes the website's performance by optimizing code, reducing file sizes, and improving loading times. A fast-loading website enhances user experience, reduces bounce rates, and improves search engine rankings", image2: "https://framerusercontent.com/images/q5h5RWImSNjBi7JmesOfZtaNOY.jpeg?scale-down-to=2048", conceptDescription: "Informing decision-making: Research provides data and evidence to support design decisions. It helps designers make informed choices about layout, color schemes, typography, and other design elements, leading to more effective and user-friendly websites", image3: "https://framerusercontent.com/images/szdQiOWLK1UFrKRNzNforAVR2vk.jpeg?scale-down-to=2048", image4: "https://framerusercontent.com/images/ss9xXtLYQbblZoYno4pKgCES8U.jpeg?scale-down-to=2048"},
        {id: 3, projectName: "hella-magic-store", projectDescription: "From spellbinding crystals to bewitching potions, our curated collection is handpicked to inspire and ignite your imagination. Browse through our shelves and uncover artifacts with ancient wisdom.", clientName: "David piagure", year: 2024, category: "business", liveProjects: "https://www.google.com/", image1: "https://framerusercontent.com/images/qBAjeNJY3IsvVWSmaixag3ucDo.jpeg?scale-down-to=2048", researchDescription: "Informing decision-making: Research provides data and evidence to support design decisions. It helps designers make informed choices about layout, color schemes, typography, and other design elements, leading to more effective and user-friendly websites", designDescription: "Usability and Accessibility: Good design considers the needs and preferences of users, ensuring that the website is easy to navigate and understand. Intuitive navigation, clear hierarchy, and logical organization of content enhance usability and accessibility, allowing users to find what they are looking for quickly and easily", developmentDescription: "Development optimizes the website's performance by optimizing code, reducing file sizes, and improving loading times. A fast-loading website enhances user experience, reduces bounce rates, and improves search engine rankings", image2: "https://framerusercontent.com/images/q5h5RWImSNjBi7JmesOfZtaNOY.jpeg?scale-down-to=2048", conceptDescription: "Informing decision-making: Research provides data and evidence to support design decisions. It helps designers make informed choices about layout, color schemes, typography, and other design elements, leading to more effective and user-friendly websites", image3: "https://framerusercontent.com/images/szdQiOWLK1UFrKRNzNforAVR2vk.jpeg?scale-down-to=2048", image4: "https://framerusercontent.com/images/ss9xXtLYQbblZoYno4pKgCES8U.jpeg?scale-down-to=2048"},
    ])

    return (
        <DataContext.Provider value={{ details }}>
            {children}
        </DataContext.Provider>
    );
};
